/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserUpdated {
  /**
   * The user-tool database ID of this user
   */
  _id: string;
  flag?: string;
  connections?: {
    twitch?: {
      name?: string;
      displayName?: string;
      id?: string;
      logo?: string;
      email?: string;
      oauthToken?: string;
      refreshToken?: string;
      expiresAt?: string;
    };
    discord?: {
      name?: string;
      oauthToken?: string;
      refreshToken?: string;
      expiresAt?: string;
    };
    speedrun?: {
      name?: string;
      token?: string;
    };
    twitter?: {
      handle?: string;
    };
  };
  phone_display?: string;
  phone_encrypted?: string;
  roles?: {
    /**
     * The event id for which this role is designated, or null if it is for all events.
     */
    event?: null | string;
    role?: {
      name?: string;
      special?: boolean;
      /**
       * A list of permission names. The available permissions can be found in the user tool settings, usually in settings.default.json, unless they are overwritten in settings.json
       */
      permissions?: string[];
    };
  }[];
}
