/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ButtonRGB {
  /**
   * ID of the button
   */
  button_id: number;
  /**
   * 8 bit red color component
   */
  button_R?: number;
  /**
   * 8 bit green color component
   */
  button_G?: number;
  /**
   * 8 bit blue color component
   */
  button_B?: number;
}
