/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ButtonPress {
  /**
   * ID of the button
   */
  button_id: number;
  /**
   * Used to troubleshoot message delivery issues
   */
  button_message_count?: number;
  /**
   * Object containing timestamps of when the button was pressed
   */
  time: {
    /**
     * Time the button was pressed in seconds since Unix epoch
     */
    unix: number;
    /**
     * Time the button was pressed in the ISO 8601 format
     */
    iso: string;
  };
}
