/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SCActiveRunChanged {
  /**
   * Short name for the physical event this message was for, usually the same as the donation tracker.
   */
  event: string;
  /**
   * Object of the run data from nodecg-speedcontrol. If this is not supplied, no run is set.
   */
  run?: {
    game?: string;
    gameTwitch?: string;
    system?: string;
    region?: string;
    release?: string;
    category?: string;
    estimate?: string;
    estimateS?: number;
    setupTime?: string;
    setupTimeS?: number;
    scheduled?: string;
    scheduledS?: number;
    relay?: boolean;
    teams: {
      name?: string;
      id: string;
      relayPlayerID?: string;
      players: {
        name: string;
        id: string;
        teamID: string;
        country?: string;
        pronouns?: string;
        social: {
          twitch?: string;
        };
        customData: {
          [k: string]: string;
        };
      }[];
    }[];
    customData: {
      [k: string]: string;
    };
    id: string;
    externalID?: string;
  };
  /**
   * Time the active run was changed.
   */
  time: {
    /**
     * Timestamp representation in the ISO 8601 format
     */
    iso: string;
    /**
     * Timestamp representation in seconds since the Unix epoch, including a fractional millisecond part
     */
    unix: number;
  };
}
