/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SCTimerChanged {
  /**
   * Short name for the physical event this message was for, usually the same as the donation tracker.
   */
  event: string;
  /**
   * Describes the way the timer has changed: started, paused, resumed, finished, reset, edited, team_finished, team_undid_finish.
   */
  desc: "started" | "paused" | "resumed" | "finished" | "reset" | "edited" | "team_finished" | "team_undid_finish";
  /**
   * If event is applicable to a team, lists their UUID here. This UUID is also used in the routing key.
   */
  teamID?: string;
  /**
   * Current copy of the timer object from nodecg-speedcontrol. See https://github.com/speedcontrol/nodecg-speedcontrol/blob/dev/types/timer.d.ts
   */
  timer: {
    [k: string]: any;
  };
  /**
   * Time the timer state changed
   */
  time: {
    /**
     * Timestamp representation in the ISO 8601 format
     */
    iso: string;
    /**
     * Timestamp representation in seconds since the Unix epoch, including a fractional millisecond part
     */
    unix: number;
  };
}
