/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NewScreenedCrowdControl {
  message: {
    /**
     * The message that WarpWorldBot originally posted in Twitch chat.
     */
    trailing: string;
    /**
     * This object represents a deserialized Twitch IRC message. Only properties that we use are listed here.
     */
    tags?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
