/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NewScreenedTweet {
  message: {
    /**
     * Contents of the tweet.
     */
    full_text: string;
  };
  user: {
    /**
     * Twitter handle of the user who sent the tweet.
     */
    name: string;
  };
}
