/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NewScreenedCheer {
  message: {
    /**
     * The message text.
     */
    trailing: string;
    /**
     * This object represents a deserialized Twitch IRC message. Only properties that we use are listed here.
     */
    tags: {
      /**
       * The display name of the user who cheered.
       */
      "display-name": string;
      /**
       * The amount of bits cheered by the user.
       */
      bits: string;
      [k: string]: unknown;
    };
  };
}
