/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DonationFullyProcessed {
  /**
   * Shorthand event string this donation is for.
   */
  event: string;
  /**
   * Unique donation ID from the database.
   */
  _id: number;
  /**
   * The name of the donor that they would like to appear as publicly (can be "(Anonymous)").
   */
  donor_visiblename: string;
  /**
   * The amount this donation is for. Currency isn't specified but is (currently) USD.
   */
  amount: number;
  /**
   * If the donation comment was accepted/rejected. Should be APPROVED or DENIED, rarely could be something else if something server side messes up; treat anything that isn't APPROVED as if it was DENIED.
   */
  comment_state: "ABSENT" | "PENDING" | "DENIED" | "APPROVED" | "FLAGGED";
  /**
   * Donator's comment. Can be blank; is made blank if their comment was rejected.
   */
  comment: string;
  /**
   * Timestamp of when the donation was received.
   */
  time_received: string;
}
