/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerStarted {
  /**
   * Short name for the physical event this message was for, usually the same as the donation tracker.
   */
  event: string;
  /**
   * Unique identifier for the instance of the running application.
   */
  uuid: string;
  /**
   * A 1-index based number for which slot the player tool is for.
   */
  playerID: number;
  /**
   * The name of the Twitch channel currently being served.
   */
  channel: string;
  /**
   * The port the server was started on. Currently it is assumed to be ran on the same computer, so assume it will be on localhost.
   */
  port: number;
  /**
   * Time the server was started.
   */
  time: {
    /**
     * Timestamp representation in the ISO 8601 format
     */
    iso: string;
    /**
     * Timestamp representation in seconds since the Unix epoch, including a fractional millisecond part
     */
    unix: number;
  };
}
