name: Generate Types

on:
  release:
    types: [ published ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    # Setup some Node stuff
    - name: Node.js setup
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: https://registry.npmjs.org/

    # Set NPM cache options
    - name: Set NPM cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Update NPM to the latest version
    - name: Update NPM installation
      run: npm install -g npm@latest

    # Checkout
    - name: Checkout this repository
      uses: actions/checkout@v2

    # Bump version
    - name: Bump version
      run: |
        npm version --no-git-tag-version ${{ github.event.release.tag_name }}
        git commit -m ${{ github.event.release.tag_name }} -a
        git push

    # Install NPM dependencies
    - name: Install NPM dependencies
      run: npm ci

    # Run the type generating script
    - name: Generate types
      run: npm run types

    # NPM publish version
    - name: NPM publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets['NPM_TOKEN'] }}
      run: npm publish --tag ${{ fromJSON('["latest", "next"]')[github.event.release.prerelease] }}
