name: Validate/Generate/NPM Publish

on:
  push:
    branches: [ master ]

  release:
    types: [ published ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    # Setup some Node stuff
    - name: Node.js setup
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: https://registry.npmjs.org/

    # Install pnpm
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9

    # Gets pnpm's store directory (for next step)
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    # Set pnpm cache options
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    # Checkout
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0

    # Set the local git user config to use the GitHub Actions bot account
    - name: Set local git config user details
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    # Install pnpm dependencies
    - name: Install pnpm dependencies
      run: |
        pnpm i --frozen-lockfile

    # Run the definition validation script
    - name: Validate definitions
      run: npm run validate

    # Run the type generating script
    - name: Generate types
      run: npm run types

    # Bump version (if releasing)
    - name: Bump version
      if: ${{ github.event_name == 'release' }}
      run: |
        npm version --no-git-tag-version ${{ github.event.release.tag_name }}
        git commit -m "Release: ${{ github.event.release.tag_name }}" -a

    # NPM publish version (if releasing)
    - name: NPM publish
      if: ${{ github.event_name == 'release' }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets['NPM_TOKEN'] }}
      run: npm publish --access public --tag ${{ fromJSON('["latest", "next"]')[github.event.release.prerelease] }}

    # Push version bump to GitHub (if releasing)
    - name: Push version bump
      if: ${{ github.event_name == 'release' }}
      run: git push
